Repository e-gineering/urlshortener, pull requests merged in 2022-10, with the labels that each got.

#10 Generate QR code
  Egineering.UrlShortener.Services/Egineering.UrlShortener.Services.csproj
  Egineering.UrlShortener.Services/Interfaces/IQRCodeService.cs
  Egineering.UrlShortener.Services/QRCodeService.cs
  Egineering.UrlShortener/Egineering.UrlShortener.csproj
  Egineering.UrlShortener/Program.cs
  Egineering.UrlShortener/appsettings.Development.json
  Egineering.UrlShortener/appsettings.json
  Egineering.UrlShortener/wwwroot/images/EG.png
Labels: hacktoberfest-accepted

#12 Add copy files after publish step
  Egineering.UrlShortener.Services/Egineering.UrlShortener.Services.csproj
Labels: bug, hacktoberfest-accepted

#13 add IsPublic flag to not show up on the homepage
  Egineering.UrlShortener.Services/AzureTableStorageService.cs
  Egineering.UrlShortener.Services/DTOs/ShortenedUrl.cs
  Egineering.UrlShortener.Services/DTOs/UrlRequest.cs
  Egineering.UrlShortener.Services/Helpers/Constants.cs
  Egineering.UrlShortener.Services/Interfaces/IAzureTableStorageService.cs
  Egineering.UrlShortener/Program.cs
Labels: enhancement, hacktoberfest-accepted

#15 Update error handling for GetUrlEntityByVanity
  Egineering.UrlShortener.Services/AzureTableStorageService.cs
Labels: bug, hacktoberfest-accepted
